sudo: false
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
install:
  - pip install -U pip tox virtualenv codecov
script:
  - tox -e coverage
after_success:
  - codecov
